Select * from customer limit 20;

--1.What is the total revenue generated by male vs female cutomers?.
Select gender,SUM(purchase_amount) as revenue 
from customer
group by gender

--2 Which customers used a discount but still spent more than the average purchase amount
Select customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (
      SELECT AVG(purchase_amount)
      FROM customer
  );

--3.Which are the top 5 products with th highest average review rating.
Select item_purchased ,AVG(review_rating) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--4.Compare the AVG Purchase Amounts b/w Standard and Express Shipping
Select shipping_type,AVG(purchase_amount)
from customer
where shipping_type in('Standard','Express')
group by shipping_type;

--5.Do subscribed customers spend more?Compare average spend and total revenue b/w sub and non sub
Select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer group by subscription_status
order by total_revenue, avg_spend desc;

--6.Which 5 products have highest percentage of purchase with discounts applied
SELECT
    item_purchased,
    ROUND(
        100.0 * SUM(
            CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END
        ) / COUNT(*),
        2
    ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--7.Segment customers into New,Returninig,and loyal
WITH customer_type AS (
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT
    customer_segment,
    COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

--8.what are the top 3 most purchased products within each category
WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders
    FROM customer
    GROUP BY category, item_purchased
),
ranked_items AS (
    SELECT
        category,
        item_purchased,
        total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY total_orders DESC
        ) AS item_rank
    FROM item_counts
)
SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM ranked_items
WHERE item_rank <= 3;

--9.are customers who are repeat buyers also likely to subscribe
Select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--10.What are the revenue contribution of each age group
SELECT age_grouped, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_grouped
ORDER BY total_revenue DESC;
